# -*- coding: utf-8 -*-
"""Day2_yallaAbhiram.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukWdAulV4B73hckrYf7ZimU_N5iTyTYI

### 1. Maximum of Three Numbers
"""

def maximum(a, b, c):
    return max(a, b, c)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

print("Maximum =", maximum(a, b, c))

"""### 2. Calculator Using Functions"""

def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a, b):
    return a * b

def div(a, b):
    # Add a check for division by zero
    if b == 0:
        return "Error! Division by zero!"
    return a / b

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
op = input("Enter operator (+,-,*,/): ")

if op == "+":
    print(add(a, b))
elif op == "-":
    print(sub(a, b))
elif op == "*":
    print(mul(a, b))
elif op == "/":
    print(div(a, b))
else:
    print("Invalid operator")

"""### 3. Prime Number Checker"""

def is_prime(n):
    if n < 2:
        return False

    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False

    return True

n = int(input("Enter a number: "))

if is_prime(n):
    print("Prime")
else:
    print("Not Prime")

"""### 4. Factorial Using Recursion"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n-1)

n = int(input("Enter a non-negative integer: "))
if n < 0:
    print("Factorial is not defined for negative numbers.")
else:
    print(factorial(n))

"""### 5. Fibonacci Series Using Function"""

def fibonacci(n):
    if n <= 0:
        print("Please enter a positive integer.")
        return

    a, b = 0, 1

    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b
    print()

n = int(input("Enter the number of Fibonacci terms: "))
fibonacci(n)

"""### 6. Student Grade Calculator"""

def grade(mark):
    if mark >= 90:
        return "A"
    elif mark >= 75:
        return "B"
    elif mark >= 50:
        return "C"
    else:
        return "F"

mark = int(input("Enter student's mark: "))
if 0 <= mark <= 100:
    print("Grade =", grade(mark))
else:
    print("Invalid mark. Please enter a value between 0 and 100.")

"""### 7. Even/Odd Checker"""

def even_odd(n):
    if n % 2 == 0:
        return "Even"
    return "Odd"

n = int(input("Enter an integer: "))
print(even_odd(n))

"""### 8. Temperature Converter"""

def c_to_f(c):
    return (c * 9/5) + 32

c = float(input("Enter temperature in Celsius: "))
print("Fahrenheit =", c_to_f(c))

"""### 9. Lambda Function for Square and Cube"""

square = lambda x: x**2
cube = lambda x: x**3

n = int(input("Enter a number: "))

print("Square =", square(n))
print("Cube =", cube(n))

"""### 10. Password Validation System"""

def validate(password):
    if len(password) >= 8:
        return "Valid Password"
    return "Invalid Password"

pwd = input("Enter Password (minimum 8 characters): ")
print(validate(pwd))

"""### 11. ATM Balance Checker"""

balance = 10000

def check_balance():
    print("Current Balance =", balance)

check_balance()

"""### 12. Electricity Bill Calculator"""

def bill(units):
    if units <= 100:
        return units * 2
    elif units <= 200:
        # For units between 101 and 200, first 100 units at 2 and rest at 3
        return (100 * 2) + ((units - 100) * 3)
    else:
        # For units above 200, first 100 at 2, next 100 at 3, rest at 5
        return (100 * 2) + (100 * 3) + ((units - 200) * 5)

units = int(input("Enter number of units consumed: "))
if units >= 0:
    print("Bill =", bill(units))
else:
    print("Units cannot be negative.")

"""### 13. Voting Eligibility Checker"""

def eligible(age):
    return age >= 18

age = int(input("Enter your age: "))

if eligible(age):
    print("Eligible to vote")
else:
    print("Not Eligible to vote")

"""### 14. Area Calculator for Shapes"""

import math

def circle(r):
    return math.pi * r * r

def rectangle(l, b):
    return l * b

r_circle = float(input("Enter radius for circle: "))
l_rect = float(input("Enter length for rectangle: "))
b_rect = float(input("Enter breadth for rectangle: "))

if r_circle >= 0:
    print("Circle Area =", circle(r_circle))
else:
    print("Radius cannot be negative.")

if l_rect >= 0 and b_rect >= 0:
    print("Rectangle Area =", rectangle(l_rect, b_rect))
else:
    print("Length and breadth cannot be negative.")

"""### 15. Simple Payroll System"""

def payroll(name, salary, bonus):
    total = salary + bonus

    print("Employee:", name)
    print("Salary: $", salary)
    print("Bonus: $", bonus)
    print("Total Pay: $", total)

name = input("Enter Employee Name: ")
salary = float(input("Enter Salary: "))
bonus = float(input("Enter Bonus: "))

if salary >= 0 and bonus >= 0:
    payroll(name, salary, bonus)
else:
    print("Salary and bonus cannot be negative.")