# -*- coding: utf-8 -*-
"""Day2_yallaAbhiram.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukWdAulV4B73hckrYf7ZimU_N5iTyTYI
"""

n = int(input("Enter number of rows: "))


print("\n1. Right Triangle of Stars")
for i in range(1, n + 1):
    print("*" * i)

print("\n2. Inverted Triangle of Numbers")
for i in range(n, 0, -1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()


print("\n3. Pascal's Triangle")
for i in range(n):
    num = 1
    print(" " * (n - i), end="")

    for j in range(i + 1):
        print(num, end=" ")
        num = num * (i - j) // (j + 1)
    print()


print("\n4. Prime Numbers")
for num in range(2, n + 1):
    is_prime = True

    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, end=" ")

workers = int(input("Enter number of workers: "))
days = int(input("Enter number of days: "))
target = int(input("Enter production target: "))

total_produced = 0
total_defects = 0

for day in range(1, days + 1):
    print(f"\nDay {day}")

    day_production = 0
    day_defects = 0

    for worker in range(1, workers + 1):

        items = int(input(f"Worker {worker} items produced: "))


        if items < 20:
            print("Skipped (less than 20 items)")
            continue

        defects = int(input(f"Worker {worker} defective items: "))

        day_production += items
        day_defects += defects

        total_produced += items
        total_defects += defects

        productivity = ((items - defects) / items) * 100

        print(f"Productivity: {productivity:.2f}%")


        if total_produced >= target:
            print("\nTarget Achieved!")
            break

    defect_rate = (day_defects / day_production * 100) if day_production > 0 else 0

    print("\n--- Daily Report ---")
    print("Items Produced:", day_production)
    print("Defective Items:", day_defects)
    print(f"Defect Rate: {defect_rate:.2f}%")

    if total_produced >= target:
        break

print("\n========== FINAL REPORT ==========")
print("Total Items Produced:", total_produced)
print("Total Defects:", total_defects)

overall_defect_rate = (
    total_defects / total_produced * 100
    if total_produced > 0 else 0
)

print(f"Overall Defect Rate: {overall_defect_rate:.2f}%")